# -*- coding: utf-8 -*-
"""practice.py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VeqoIe2eBfSTSfpT-QTx_-ZmO7Yoip7i


"""# 1.	Road traffic Violation Fine Calculator
Instructions:
You are tasked with creating a traffic violation fine calculator for a traffic police department. The program should calculate the fine based on the violation type. Develop a Python program that takes the violation type as input and outputs the corresponding fine amount.
Details:
Input the violation type from the user (e.g., "overspeeding", "wrong_signal").
Use if-elif statements to determine the fine amount based on the violation type:
"overspeeding": Fine = Rs. 1000
"wrong_signal": Fine = Rs. 500
Other violations: Fine = Rs. 300

"""

rules = ["overspeeding" , "wrongsignal" , "other"]

for index in range(len(rules)):
    value = rules[index]
    print(index, value)

violations = input("Enter violations: ")

if violations == rules[0]:
    print(f"you violated the {violations} so the fine on you is Rs 1000")
elif violations == rules[1]:
        print(f"you violated the {violations} so the fine on you is Rs 500")
elif violations == rules[2]:
        print(f"you violated the {violations} so the fine on you is Rs 300")
else:
    print("Invalid Value")

"""# 2.	Electricity Bill Calculation
Instructions:
You are tasked with designing an electricity bill calculator for a local utility company. The program should calculate the bill amount based on the units of electricity consumed. Develop a Python program that takes the units consumed as input and calculates the bill.
Details:
Input the units of electricity consumed from the user.
Use if-elif statements to calculate the bill amount based on different usage slabs:
Up to 100 units: Rs. 5 per unit
101 to 200 units: Rs. 7 per unit
Above 200 units: Rs. 10 per unit
Display the calculated bill amount.

"""

units = int(input("Enter Your Consumed Units: "))

if units <= 100:
    print(f"You Consumed : {units} units & your bill is :{units*5}")
elif units == 101 and units <= 200:
    print(f"You Consumed : {units} units & your bill is :{units*7}")
elif units > 200:
    print(f"You Consumed : {units} units & your bill is :{units*10}")

"""# 3.	Admission Eligibility Checker
Instructions:
A prestigious university in Lahore wants to streamline its admission process. Develop a Python program that takes a student's entry test score as input and determines their eligibility for admission.
Details:
Input the student's entry test score.
Use an if-else statement to check if the score meets the minimum eligibility criteria (e.g., score >= 70).

"""

score = int(input("Enter Your Test Score: "))

if score >=70:
    print(f"You secured {score} marks and you are eligible in this prestigious university ")
else:
    print("You are not eligible ")

"""# 4.	Grocery Shopping Discounts
Instructions:
A supermarket in Islamabad is offering discounts based on the total bill amount. Create a Python program that takes the total bill amount as input and calculates the applicable discount.
Details:
Input the total bill amount.
Use if-elif statements to calculate the discount based on different bill ranges:
Bill >= Rs. 1000: 10% discount
Bill >= Rs. 500: 5% discount
No discount for bills below Rs. 500
Display the calculated discount amount and the final payable amount.

"""

bill_amount = (int(input("Please Enter Your Bill Amount :")))

if bill_amount >=1000:
    print(f"Your amount is {bill_amount} RS. & you got discount 10%,Now pay bill: {bill_amount-bill_amount*0.10}")
elif  bill_amount >=500:
    print(f"Your amount is {bill_amount} RS. & you got discount 10%,Now pay bill: {bill_amount-bill_amount*0.05}")
else:
    print("No discount for bills below Rs. 500")

"""# 5.	Train Fare Calculator
Instructions:
Pakistan Railways wants to provide an automated fare calculation system for passengers. Develop a Python program that takes the distance of the journey in kilometers and calculates the fare based on travel class.
Details:
Input the distance of the journey in kilometers.
Input the travel class (economy, business, first).
Use if-elif statements to calculate the fare based on travel class:
Economy: Rs. 10 per km
Business: Rs. 15 per km
First: Rs. 20 per km
Display the calculated fare for the journey.

"""

distance = int(input("Input the distance of the journey in kilometers: "))
travel_Class = input("Input the travel class (economy, business, first).")

if travel_Class == "economy":
    print(f"your fare is {distance*10}")
elif  travel_Class == "business":
    print(f"your fare is {distance*15}")
elif  travel_Class == "first":
    print(f"your fare is {distance*20}")

"""#6  A restaurant in Lahore wants to provide personalized menu suggestions to customers. Develop a Python program that takes a customer's dietary preference (vegetarian or non-vegetarian) as input and suggests menu items accordingly.
Details:
Input the customer's dietary preference (vegetarian or non-vegetarian).
Use if-elif statements to suggest menu items based on the preference:
Vegetarian: Offer vegetable biryani, paneer tikka, and dal makhani.
Non-vegetarian: Offer chicken karahi, seekh kebabs, and mutton biryani.
Display the suggested menu items.

"""

customer = input("vegetarian or non-vegetarian")

if customer == "vegetarian":
    menu = ["vegetable biryani" , "paneer tikka" , "dal makhani"]
    print(menu)
elif customer =="non-vegetarian":
    menu = ["chicken karhai", "seekh kabab" , "mutton biryani"]
    print(menu)

